// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportMicroservice.Infrastructure.Concrete.EntityFramework.Context;

#nullable disable

namespace ReportMicroservice.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReportMicroservice.Entity.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MeterSerialNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LunaReports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b896c024-e0d6-49dc-a1f4-dd3e34d58a34"),
                            CreatedOn = new DateTime(2024, 6, 19, 20, 29, 26, 132, DateTimeKind.Local).AddTicks(6719),
                            IsDeleted = false,
                            MeterSerialNo = "aaAa11aa",
                            RequestedDate = new DateTime(2024, 6, 19, 20, 29, 26, 132, DateTimeKind.Local).AddTicks(6731),
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
