// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportMicroservice.Infrastructure.Concrete.EntityFramework.Context;

#nullable disable

namespace ReportMicroservice.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReportMicroservice.Entity.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MeterSerialNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LunaReports");

                    b.HasData(
                        new
                        {
                            Id = "2bf0e223-c217-4980-b839-b8af458709f9",
                            CreatedOn = new DateTime(2024, 6, 21, 1, 54, 28, 672, DateTimeKind.Local).AddTicks(6843),
                            IsDeleted = false,
                            MeterSerialNo = "aaAa11aa",
                            RequestedDate = new DateTime(2024, 6, 21, 1, 54, 28, 672, DateTimeKind.Local).AddTicks(6854),
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
