// <auto-generated />
using System;
using MeterMicroservice.Infrastructure.Concrete.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeterMicroservice.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240620213500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeterMicroservice.Entity.Meter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("CurrentValue")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LastIndex")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeasurementTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MeterSerialNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("VoltageValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Meters");

                    b.HasData(
                        new
                        {
                            Id = "da119dc7-9083-4b53-95c8-0f1ab2ea9f16",
                            CreatedOn = new DateTime(2024, 6, 21, 0, 35, 0, 288, DateTimeKind.Local).AddTicks(4815),
                            CurrentValue = 10.0,
                            IsDeleted = false,
                            LastIndex = 2,
                            MeasurementTime = new DateTime(2024, 6, 21, 0, 35, 0, 288, DateTimeKind.Local).AddTicks(4829),
                            MeterSerialNo = "aaAa11aa",
                            VoltageValue = 10.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
